blank_issues_enabled: false
contact_links:
  - name: ðŸ’¡ Feature Request
    url: https://github.com/khulnasoft/react-bridging/discussions/new?category=proposals
    about: If you've got an idea for a new feature in React Bridging, please open a new Discussion with the `Proposals` label
  - name: ðŸ¤” Usage Question (Github Discussions)
    url: https://github.com/khulnasoft/khulnasoft/discussions/new?category=q-a
    about: Open a Discussion in GitHub wih the `Q&A` label
  - name: ðŸ’¬ KhulnaSoft Discord Channel
    url: https://discord.khulnasoft.com
    about: Interact with other people using React Bridging and Remix ðŸ“€
